#!/bin/sh
SERVICE_NAME="Network Monitor"
PIDFILE="/var/run/network-monitor.pid"

if [ ! -f /mnt/config/netmon.conf ]; then
  echo "You have to configure network monitor first. Please see /mnt/config/netmon.conf for further instructions"
fi

status()
{
  pid="$(cat "$PIDFILE" 2>/dev/null)"
  if [ "$pid" ]; then
    kill -0 "$pid" >/dev/null && echo "PID: $pid" || return 1
  fi
}

start()
{
  if status >/dev/null 2>&1; then
    echo "Network Monitor already running"
    return 0
  fi
  rm -f "$PIDFILE" >/dev/null 2>&1 || true
  echo "Starting Network Monitor"
  /mnt/bin/busybox nohup /mnt/scripts/network-monitor.sh >/dev/null 2>&1 &
  echo "$!" > "$PIDFILE"
}

stop()
{
  pid="$(cat "$PIDFILE" 2>/dev/null)"
  if [ "$pid" ]; then
     kill "$pid" && rm "$PIDFILE"
  fi
}

restart()
{
  stop >/dev/null 2>&1 || true
  sleep 1
  start
}

if [ $# -eq 0 ]; then
  start
else
  case $1 in start|stop|status|restart)
    $1
    ;;
  esac
fi
