#!/bin/sh
SERVICE_NAME="Red Led"
export LD_LIBRARY_PATH='/mnt/lib/:/lib/:/usr/lib/'

. /mnt/scripts/common_functions.sh

status()
{
  state="$(red_led status 2>/dev/null)"
  case "$state" in
    ON|on)
      echo "PID: OK"
      ;;
  esac
}

start()
{
  blue_led off
  red_led on
}

stop()
{
  red_led off
}

if [ $# -eq 0 ]; then
  start
else
  case $1 in start|stop|status)
    $1
    ;;
  esac
fi
