#!/bin/bash
# Comprehensive Deployment Script for TECKIN TC100 Hacks
# Automatically generated by Antigravity

set -e

STAGING_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FTP_HOST="192.168.1.24"
FTP_PORT="2121"
FTP_USER="root"
FTP_PASS="pass"
FTP_URL="ftp://$FTP_USER:$FTP_PASS@$FTP_HOST:$FTP_PORT"

# Colors for output
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}=== Deploying TECKIN TC100 Hacks to $FTP_HOST:$FTP_PORT ===${NC}"

# List of directories to upload (local relative path : remote destination)
DIRS_TO_UPLOAD=(
  "bin"
  "config"
  "controlscripts"
  "lib"
  "scripts"
  "www"
  "sounds"
)

# Individual files to upload
FILES_TO_UPLOAD=(
  "autorun.sh"
  "AUDIO_FEATURES.md"
  "IMPLEMENTATION_SUMMARY.md"
  "README.md"
)

upload_file() {
    local local_file="$1"
    local remote_path="$2"
    local filename=$(basename "$local_file")
    
    # Ensure remote path starts with /mnt/
    if [[ ! "$remote_path" == /mnt/* ]]; then
        remote_path="/mnt/$remote_path"
    fi

    echo -ne "  ${YELLOW}↑ $remote_path${NC} ... "
    
    # Special handling for potentially busy binaries in /mnt/bin
    if [[ "$remote_path" == /mnt/bin/* ]]; then
        # Try to rename the existing binary to .old to bypass 'file busy' errors
        curl -s -P - -Q "RNFR $remote_path" -Q "RNTO $remote_path.old" "$FTP_URL" > /dev/null 2>&1 || true
    fi

    if curl -s -P - --ftp-create-dirs -T "$local_file" "$FTP_URL$remote_path" > /dev/null; then
        echo -e "${GREEN}OK${NC}"
        return 0
    else
        echo -e "${RED}FAILED${NC}"
        return 1
    fi
}

# Upload individual files first
echo -e "\n${BLUE}Uploading core files...${NC}"
for file in "${FILES_TO_UPLOAD[@]}"; do
    if [ -f "$STAGING_DIR/$file" ]; then
        upload_file "$STAGING_DIR/$file" "/mnt/$file"
    else
        echo -e "  ${RED}✗ Missing: $file${NC}"
    fi
done

# Upload directories recursively
echo -e "\n${BLUE}Uploading directories...${NC}"
for dir in "${DIRS_TO_UPLOAD[@]}"; do
    if [ -d "$STAGING_DIR/$dir" ]; then
        echo -e "${YELLOW}Processing directory: $dir${NC}"
        find "$STAGING_DIR/$dir" -type f | while read -r file; do
            # Compute relative path from workspace root
            rel_path="${file#$STAGING_DIR/}"
            upload_file "$file" "/mnt/$rel_path"
        done
    else
        echo -e "  ${RED}✗ Missing directory: $dir${NC}"
    fi
done

echo -e "\n${GREEN}=== Deployment Complete ===${NC}"
